curl -u admin:zaq12345 -X PUT --data-binary @data/nlp/models/en-chunker.bin -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/en-chunker.bin
curl -u admin:zaq12345 -X PUT --data-binary @data/nlp/models/en-ner-date.bin -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/en-ner-date.bin
curl -u admin:zaq12345 -X PUT --data-binary @data/nlp/models/en-ner-location.bin -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/en-ner-location.bin
curl -u admin:zaq12345 -X PUT --data-binary @data/nlp/models/en-ner-money.bin -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/en-ner-money.bin
curl -u admin:zaq12345 -X PUT --data-binary @data/nlp/models/en-ner-organization.bin -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/en-ner-organization.bin
curl -u admin:zaq12345 -X PUT --data-binary @data/nlp/models/en-ner-percentage.bin -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/en-ner-percentage.bin
curl -u admin:zaq12345 -X PUT --data-binary @data/nlp/models/en-ner-person.bin -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/en-ner-person.bin
curl -u admin:zaq12345 -X PUT --data-binary @data/nlp/models/en-ner-time.bin -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/en-ner-time.bin
curl -u admin:zaq12345 -X PUT --data-binary @data/nlp/models/en-parser-chunking.bin -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/en-parser-chunking.bin
curl -u admin:zaq12345 -X PUT --data-binary @data/nlp/models/en-pos-perceptron.bin -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/en-pos-perceptron.bin
curl -u admin:zaq12345 -X PUT --data-binary @data/nlp/models/en-sent.bin -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/en-sent.bin
curl -u admin:zaq12345 -X PUT --data-binary @data/nlp/models/en-token.bin -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/en-token.bin
curl -u admin:zaq12345 -X PUT --data-binary @data/nlp/models/nl-token.bin -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/nl-token.bin
curl -u admin:zaq12345 -X PUT --data-binary @data/nlp/models/defmodel.events -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/defmodel.events