curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/abbreviations.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/abbreviations.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/adbc.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/adbc.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/airport.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/airport.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/airports.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/airports.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/cdg.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/cdg.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/charities.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/charities.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/city.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/city.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/city_cap.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/city_cap.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/city_uk.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/city_uk.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/colours.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/colours.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/company.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/company.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/company_cap.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/company_cap.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/country.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/country.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/country_abbrev.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/country_abbrev.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/country_adj.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/country_adj.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/country_cap.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/country_cap.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/currency_prefix.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/currency_prefix.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/currency_unit.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/currency_unit.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/date.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/date.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/date_key.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/date_key.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/date_post.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/date_post.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/date_pre.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/date_pre.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/date_unit.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/date_unit.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/datespan.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/datespan.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/day.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/day.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/day_cap.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/day_cap.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/department.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/department.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/determiner.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/determiner.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/facility.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/facility.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/facility_key.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/facility_key.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/facility_key_ext.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/facility_key_ext.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/festival.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/festival.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/govern_key.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/govern_key.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/government.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/government.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/greeting.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/greeting.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/hour.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/hour.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/ident_prekey.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/ident_prekey.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/jobtitles.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/jobtitles.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/loc_generalkey.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/loc_generalkey.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/loc_key.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/loc_key.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/loc_prekey.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/loc_prekey.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/loc_prekey_lower.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/loc_prekey_lower.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/loc_relig.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/loc_relig.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/ministry.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/ministry.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/minutes.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/minutes.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/months.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/months.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/months_lower.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/months_lower.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/mountain.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/mountain.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/new_adj.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/new_adj.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/new_cdg.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/new_cdg.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/newspapers.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/newspapers.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/non_company.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/non_company.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/nonspec_date.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/nonspec_date.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/not_org.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/not_org.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/number_fold.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/number_fold.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/numbers.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/numbers.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/ordinal.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/ordinal.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/org_base.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/org_base.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/org_ending.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/org_ending.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/org_key.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/org_key.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/org_key_cap.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/org_key_cap.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/org_pre.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/org_pre.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/org_spur.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/org_spur.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/organization.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/organization.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/organization_nouns.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/organization_nouns.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/other_people.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/other_people.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/othorg_key.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/othorg_key.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/percent.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/percent.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/person_ambig.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/person_ambig.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/person_ambig.old.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/person_ambig.old.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/person_ambig2.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/person_ambig2.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/person_ambig_lower.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/person_ambig_lower.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/person_ending.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/person_ending.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/person_female.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/person_female.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/person_female_cap.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/person_female_cap.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/person_female_lower.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/person_female_lower.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/person_first.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/person_first.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/person_full.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/person_full.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/person_male.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/person_male.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/person_male_cap.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/person_male_cap.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/person_male_lower.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/person_male_lower.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/person_relig.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/person_relig.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/person_sci.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/person_sci.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/person_spur.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/person_spur.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/phone_prefix.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/phone_prefix.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/planet.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/planet.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/province.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/province.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/province_aa.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/province_aa.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/province_ab.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/province_ab.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/racecourse.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/racecourse.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/region.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/region.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/region_cap.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/region_cap.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/region_uk.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/region_uk.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/rivers.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/rivers.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/sports.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/sports.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/spur.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/spur.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/spur_ident.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/spur_ident.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/stop.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/stop.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/street.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/street.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/surname_prefix.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/surname_prefix.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/team.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/team.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/time.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/time.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/time_ampm.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/time_ampm.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/time_key.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/time_key.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/time_modifier.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/time_modifier.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/time_unit.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/time_unit.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/times.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/times.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/timespan.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/timespan.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/timex_pre.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/timex_pre.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/timezone.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/timezone.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/title.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/title.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/title_female.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/title_female.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/title_lower.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/title_lower.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/title_lowercase.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/title_lowercase.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/title_male.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/title_male.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/title_mil.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/title_mil.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/title_pol.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/title_pol.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/tvcompany.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/tvcompany.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/water.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/water.lst
curl -u admin:password123 -X PUT --data-binary @data/nlp/gazetteer/year.lst -H "Content-type: application/octet-stream" http://localhost:8764/api/apollo/blobs/year.lst
